//style
import './globals.css'
//meta data
import type { Metadata } from 'next'
//google fonts
import { Alex_Brush, Montserrat } from 'next/font/google'
//components
import Footer from '@/components/Footer'
import Header from '@/components/Header'
//context provider
import NavContextProvider from '@/context/NavContext'

//google font Alex_Brush
const alexBrush = Alex_Brush({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-alexbrush',
})

//google font montserrat
const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

//meta
export const metadata: Metadata = {
  title: 'Mia Reynolds',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <NavContextProvider>
      <html lang="en">
        <body
          className={`${alexBrush.variable} ${montserrat.variable} overflow-x-hidden relative`}
        >
          <div className="flex flex-col h-full">
            <Header />
            <div className="flex-auto">{children}</div>
            <Footer />
          </div>
        </body>
      </html>
    </NavContextProvider>
  )
}
